### ISSUE TITLE
Design the initial UI/UX of the web app

### ISSUE THREAD

**Issue by mhaidarhanif** [amadzuki/saikou#2]
The initial pages are:

- Home
- About
- AnimeCollection
- Anime

**Comment by mhaidarhanif** [comment]
The design is on Figma: https://www.figma.com/file/j4lco2gQyoGtrY47DnzoTl/Saikou

**Comment by amadzuki** [comment]
Today I'll try to finish those initial pages in figma

**Comment by mhaidarhanif** [comment]
@amadzuki What are your favorites anime and manga? List them here.

**Comment by mhaidarhanif** [comment]
My favorite anime:

- Fullmetal Alchemist: Brotherhood
- Nanatsu No Taizai (The Seven Deadly Sins)
- Dragon Ball Super
- Shingeki no Kyojin (Attack on Titan)
- Boku no Hero Academia
- Dr. Stone
- Death Note
- Food Wars!: Shokugeki no Soma
- One Punch Man
- Code Geass
- The Disastrous Life of Saiki K.
- Hunter x Hunter
- No Game No Life
- Kimi no Na wa
- Pokemon
- Digimon

My favorite manga:

- The Seven Deadly Sins
- Dr. Stone
- One Punch Man
- Death Note
- Black Clover
- Dragon Ball Super
- Eyeshield 21

**Comment by amadzuki** [comment]
My Favorite Anime:

- Code Geass
- Boku no Hero Academia
- One Punch Man
- Death Note
- Black Clover
- Fullmetal Alchemist: Brotherhood
- No Game No Life
- Hyouka
- K-On
- Kimetsu no Yaiba
- Shingeki no Kyojin
- Haikyu!
- Kuroko no Basket
- SAO
- Steins;Gate
- Re:Zero kara Hajimeru Isekai Seikatsu
- Kimi no Nawa
- Tokyo Ghoul
- Gintama

My Favorite Manga: 

- Naruto
- One Piece
- Bleach
- Tokyo Ghoul
- Vinland Saga
- Kami nomi zo Shiru Sekai
- Horimiya
- Onanie Master Kurosawa
- 21st Century Boys
- Shin Angyo Onshi
- Doraemon
- Tensei shitara Slime Datta Ken
- Machida-kun no Sekai
- Magi: The Labyrinth of Magic
- Imawa no Kuni no Alice
- Konjiki no Gash!!
- Suashi no Meteorite
- Berserk
- Beelzebub

**Comment by amadzuki** [comment]
I've finished the initial pages. Thanks for the guidance @mhaidarh.

I've added some more manga to the list too and plan to work on the its page design tomorrow.

Here's the figma link: https://www.figma.com/file/j4lco2gQyoGtrY47DnzoTl/Saikou?node-id=0%3A1

**Comment by mhaidarhanif** [comment]
Nice, you're welcome @amadzuki

Keep up the good work

You can also state your plan for today on Slack. I already sent you the questions.
