### ISSUE TITLE
Design manga-related pages

### ISSUE THREAD

**Issue by amadzuki** [amadzuki/saikou#3]
They consist of these following pages: 

- MangaCollection
- Manga
- MangaReview

[Here's the Figma file](https://www.figma.com/file/j4lco2gQyoGtrY47DnzoTl/Saikou?node-id=0%3A1)

**Comment by mhaidarhanif** [comment]
Got it. You can also separate the Search work into different issue.

**Comment by mhaidarhanif** [comment]
I've separated it: https://github.com/amadzuki/saikou/issues/4

**Comment by amadzuki** [comment]
Okay Sir, I'll try to get it done today

**Comment by mhaidarhanif** [comment]
You can also decide and improve on the colorings.

As in the Anime page, it is done but the colors and user avatars are not shown yet.

<img width="471" alt="Screenshot 2020-07-03 at 14 48 26" src="https://user-images.githubusercontent.com/235584/86445341-68133c80-bd3c-11ea-9ee4-d2ae8a80d5bb.png">

**Comment by amadzuki** [comment]
I've filled the avatars but I think the color quite good as it is 
(apparently, I'm quite bad at choosing color. So I'll leave it for now)
