### ISSUE TITLE
Design search page

### ISSUE THREAD

**Issue by mhaidarhanif** [amadzuki/saikou#4]
Design search page.

**Comment by amadzuki** [comment]
Should I design this page including all the case @mhaidarh ?

I mean, for example: 
- search page in case of no result
- search page in case of manga result
- search page in case of anime result

**Comment by amadzuki** [comment]
I've created the search page with aggregated result of manga and anime differentiated by tags.

In case of no result, I've created one more page design telling the user the result of inputted keyword is not found and also show some suggestions.
