### ISSUE TITLE
Design footer component

### ISSUE THREAD

**Issue by mhaidarhanif** [amadzuki/saikou#5]
Right now Saikou doesn't have any footer yet. A "saikou no website" should have a footer. haha. The footer should be available on all pages. So you make it as a component, then the instances are on each pages.

The footer contains:

- Logo, inverted version (if the background is dark).
- Sitemap. Similar to navigation, but can contain other links such as social media icons.
- Copyright
- Repo to GitHub link

Can be more or modified based on conditions.

**Comment by amadzuki** [comment]
Footer component done. More component can be added later if necessary.
