### ISSUE TITLE
Design Register, Login and Logout page

### ISSUE THREAD

**Issue by amadzuki** [amadzuki/saikou#6]
Design Register, Login and Logout page on figma.

See it with this [link](https://www.figma.com/file/j4lco2gQyoGtrY47DnzoTl/Saikou?node-id=0%3A1)

**Comment by mhaidarhanif** [comment]
@amadzuki You also need to require an email input field.

**Comment by amadzuki** [comment]
Ah, right. on it

**Comment by amadzuki** [comment]
I've done the least. I think more detailed things such the UX for registration flows can be decided alongside client and server implementation. I will make new issue for it later.
